DROP TABLE user if EXISTS;
CREATE TABLE user(
    id bigint(10) generated by DEFAULT as IDENTITY,
    username VARCHAR (40),
    name VARCHAR (30),
    age int(3),
    balance DECIMAL(10,2),
    PRIMARY KEY(id)
)